title: Fan Peng Homework
author: FanPeng
email: fanpeng1001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  github studying.

# social links
twitter_username: fanpeng1001 # DO NOT include the @ character, or else the build will fail!
github_username:  fp-09 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
